libs:
	cd syscall; $(MAKE)
	cd util; $(MAKE)
	cd primitive_print; $(MAKE)
	cd debug_print; $(MAKE)
	cd test_print; $(MAKE)
	cd tell_kernel; $(MAKE)

clean:
	cd syscall; $(MAKE) clean
	cd util; $(MAKE) clean
	cd primitive_print; $(MAKE) clean
	cd debug_print; $(MAKE) clean
	cd test_print; $(MAKE) clean
	cd tell_kernel; $(MAKE) clean
	
