libs:
	cd std; $(MAKE)
	cd util; $(MAKE)
	cd primitive_print; $(MAKE)
	cd debug_print; $(MAKE)
	cd test_print; $(MAKE)
	cd sys; $(MAKE)

clean:
	cd std; $(MAKE) clean
	cd util; $(MAKE) clean
	cd primitive_print; $(MAKE) clean
	cd debug_print; $(MAKE) clean
	cd test_print; $(MAKE) clean
	cd sys; $(MAKE) clean
	
